[default]
#SQLALCHEMY_DATABASE_URI = ''
TITLE = 'Stock Prisma'
#SECRET_KEY = "JSHSHJDS"
EXTENSIONS = [
    "stock_prisma.blueprints.views",
    "stock_prisma.blueprints.restapi"
]

#[production]
#SQLALCHEMY_DATABASE_URI = '' #apontar o banco de dados que foi criado