[default]
#SQLALCHEMY_DATABASE_URI = ''
TITLE = 'Stock Prisma'

DB_USER = "postgres"
DB_HOST = "db.rkhgiwvevpobkzxtbfpk.supabase.co"
DB_PORT = 5432
DB_NAME = "postgres"

SQLALCHEMY_DATABASE_URI = "@format postgresql://{this.DB_USER}:{env[DB_PASSWORD]}@{this.DB_HOST}:{this.DB_PORT}/{this.DB_NAME}"

EXTENSIONS = [
    "stock_prisma.ext.database",
    "stock_prisma.blueprints.views",
    "stock_prisma.blueprints.restapi"
]

#[production]
